Add Max Speed per drive information
teslamate-org/teslamate pull request #2638
Opened 2022-05-02 09:45 UTC by jonferreira

2022-06-24 11:14 UTC, adriankumpf requested changes
Thanks for the PR!

The max speed is not a good fit for the Trip dashboard as it is meant to be display only the most important drive related information. It could be added to the Drives dashboard though.

2022-06-24 11:14 UTC, adriankumpf commented on grafana/dashboards/trip.json
> +          "rawSql": "WITH data AS (\n  SELECT\n    round(extract(epoch FROM start_date)) * 1000 AS start_date_ts,\n    round(extract(epoch FROM end_date)) * 1000 AS end_date_ts,\n    car.id as car_id
Drives already have a `speex_max` column

2022-06-24 11:14 UTC, adriankumpf commented on grafana/dashboards/trip.json
> +                "value": "lengthkm"
This should be `km/h`

2022-06-24 11:14 UTC, adriankumpf commented on grafana/dashboards/trip.json
> +              "options": "speed_max_kmh"
Another matcher would have to be added for mph :)

2023-11-13 01:07 UTC, Dulanic commented
Closing, if want to add, need to rebase and adjust per feedback. If someone else wants to take over, resubmit. Agree that this does not belong in trip.

2023-11-13 01:07 UTC, closed without merging