Support listening on unix domain socket
teslamate-org/teslamate pull request #3328
Opened 2023-09-01 13:31 UTC by PhracturedBlue

This patch allows listening on  a unix-domain-socket instead of via TCP.  This is useful when using rootless containers without slirp4netns by exposing the unix socket through the host rather than mapping unix ports.  In my case, it allows me to run a reverse-proxy with --network=none as it only speaks to unix sockets, and listens on a systemd socket-activated socket.

To use, specify:
 * HTTP_BINDING_ADDRESS=<absolute path to binding socket>
 * ~PORT=0~

2023-11-16 08:08 UTC, JakobLichterfeld approved these changes
lgtm

2024-01-19 14:42 UTC, JakobLichterfeld commented
Please add documentation as well

2024-01-27 15:58 UTC, PhracturedBlue commented
I have pushed an update with documentation along with some improvements.  ranch >= 2.0 is needed to properly support auto-removal and permission-setting of the unix-domain-socket.

2024-01-27 16:11 UTC, JakobLichterfeld requested changes
Thanks for the change and the documentation!

2024-01-27 16:11 UTC, JakobLichterfeld commented on website/docs/guides/unix_domain_sockets.md
> +Nginx requires that the UDS exist when it is started, but Teslamate will (re)create the UDS on startup.  This means that Teslamate must be configured to start before Nginx, or Nginx must be configure
"This directory e unix-somain-socket" ?

2024-01-27 16:11 UTC, JakobLichterfeld commented on website/docs/guides/unix_domain_sockets.md
> +It is possible to configure Teslamate to communicate over unix-domain sockets (UDS) instea of a typical network socket.  This can be useful to improve security by restricting which applications can c
Should be "**b**eyond the scope"

2024-01-27 16:26 UTC, PhracturedBlue commented on website/docs/guides/unix_domain_sockets.md
> +It is possible to configure Teslamate to communicate over unix-domain sockets (UDS) instea of a typical network socket.  This can be useful to improve security by restricting which applications can c
Thanks for looking it over.  Fixed

2024-01-29 12:41 UTC, JakobLichterfeld approved these changes

2024-01-29 12:43 UTC, merged