Add Thai Translation
teslamate-org/teslamate pull request #3566
Opened 2023-12-14 08:13 UTC by tomzt

- Create Folder For Thai 
- Translate two file in to Thai Language

2024-01-02 10:44 UTC, tomzt commented
Hi, Maintainers 
Any suggestions to fix it?

2024-01-11 17:57 UTC, JakobLichterfeld commented
Thanks for your change!

2024-01-11 17:58 UTC, JakobLichterfeld commented
The build fails due to invalid symbols, so we can not merge this in this state.

2024-01-12 13:01 UTC, JakobLichterfeld requested changes

2024-01-12 13:01 UTC, JakobLichterfeld commented on priv/gettext/th/LC_MESSAGES/default.po
> +msgstr เพื่อให้แน่ใจว่า <strong>โทเค็น Tesla API ของคุณจะถูกเก็บไว้อย่างปลอดภัย</strong> จะต้องมอบคีย์การเข้ารหัสให้กับ TeslaMate ผ่านทางตัวแปรสภาพแวดล้อม <code>ENCRYPTION_KEY</code> มิฉะนั้น <strong
This needs to be "เพื่อให้แน่ใจว่า...

2024-01-12 14:48 UTC, tomzt commented on priv/gettext/th/LC_MESSAGES/default.po
> +msgstr เพื่อให้แน่ใจว่า <strong>โทเค็น Tesla API ของคุณจะถูกเก็บไว้อย่างปลอดภัย</strong> จะต้องมอบคีย์การเข้ารหัสให้กับ TeslaMate ผ่านทางตัวแปรสภาพแวดล้อม <code>ENCRYPTION_KEY</code> มิฉะนั้น <strong
completed

2024-02-02 03:43 UTC, tomzt commented
@JakobLichterfeld Any suggestions ?

2024-02-02 08:05 UTC, JakobLichterfeld requested changes

2024-02-02 08:05 UTC, JakobLichterfeld commented on priv/gettext/th/LC_MESSAGES/default.po
> +msgid "There is <strong>%{n} charging session</strong> at this location for which no costs have been added yet."
This is not correct

2024-02-05 04:00 UTC, tomzt commented
@JakobLichterfeld review again, Thanks

2024-02-05 18:23 UTC, JakobLichterfeld commented
Perfect, ty!

2024-02-05 18:23 UTC, merged