small visual distinguish between AC & DC charging in charges dashboard and unification of the DC coloring in all dashboards
teslamate-org/teslamate pull request #4124
Opened 2024-08-05 15:39 UTC by stauffenberg2020

This commit just adds a different colour to the DC charges so that it can be easily visualized

![image](https://github.com/user-attachments/assets/af406b4c-7d4c-4b69-9d2d-414bc24950dd)

2024-08-06 08:41 UTC, JakobLichterfeld commented
Thanks for your suggestion!

May I ask to align the color to Chargin Stats?

2024-08-06 13:45 UTC, JakobLichterfeld commented
> So should I change the charging stats dashboard to orange so that DC is represented by orange color in all these 3 dashboards?

That would be awesome!

2024-08-06 14:06 UTC, JakobLichterfeld requested changes
Thanks for your change

2024-08-06 14:06 UTC, JakobLichterfeld commented on grafana/dashboards/charges.json
> +                        "color": "orange",
this should be `light-orange` as well

2024-08-06 14:42 UTC, JakobLichterfeld approved these changes
now it looks perfect

2024-08-06 14:45 UTC, merged

2024-08-07 23:36 UTC, sdwalker commented
The battery health and charge pie chart greens are different as well

I agree with getting a consistent shade of colors used throughout all of the dashboards