fixes #2839 - render relative time via sql instead of grafana
teslamate-org/teslamate pull request #4164
Opened 2024-08-28 09:35 UTC by swiffer

2024-08-29 16:36 UTC, JakobLichterfeld requested changes
Awesome, ty.

2024-08-29 16:36 UTC, JakobLichterfeld commented on grafana/dashboards/updates.json
> +      "pluginVersion": "11.2.0",
we are using 11.0.1 currently, aren't we?

2024-08-29 16:48 UTC, swiffer commented on grafana/dashboards/updates.json
> +      "version": "11.2.0"
True, I started testing Grafana 11.2.0 locally and did an export using Grafana 11.2.0. It shouldn't make a difference, if you like I can remove the changes not needed for now?

2024-08-30 07:26 UTC, JakobLichterfeld commented on grafana/dashboards/updates.json
> +      "version": "11.2.0"
Yeah, would like to keep the PR only related to the issue and not mixing it up

2024-09-03 08:26 UTC, swiffer commented
@JakobLichterfeld - done ;)

2024-09-03 08:57 UTC, JakobLichterfeld approved these changes
perfect, ty

2024-09-03 09:05 UTC, merged