docs: Introducing TeslaMate Guru on Gurubase.io
teslamate-org/teslamate pull request #4390
Opened 2024-11-18 19:24 UTC by kursataktas

Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [TeslaMate Guru](https://gurubase.io/g/teslamate) to Gurubase. TeslaMate Guru uses the data from this repo and data from the [docs](https://docs.teslamate.org) to answer questions by leveraging the LLM.

In this PR, I showcased the "TeslaMate Guru", which highlights that TeslaMate now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable TeslaMate Guru in Gurubase, just let me know that's totally fine.

2024-11-18 19:29 UTC, cwanja commented
Not a huge fan of updating the READMIE file, we do not own this project. Would rather update the Projects using TeslaMate docs page. 
https://docs.teslamate.org/docs/projects

2024-11-19 08:14 UTC, JakobLichterfeld commented
Thanks for your PR.

Without looking deeper into it, it sounds like a nice usecase of LLM.

Regarding any link to gurubase in TeslaMate repo, I'm totally on cwanaja's side:

> Not a huge fan of updating the README file, we do not own Guru project. Would rather update the Projects using TeslaMate docs page.

2024-11-19 14:45 UTC, JakobLichterfeld requested changes
see https://github.com/teslamate-org/teslamate/pull/4390#issuecomment-2484993258

2024-11-20 07:43 UTC, JakobLichterfeld approved these changes
Thanks!

2024-11-20 08:09 UTC, merged

2024-11-25 21:58 UTC, kursataktas commented
Hi @JakobLichterfeld,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

2025-01-16 11:20 UTC, kursataktas commented
Hello Everyone,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.